# Generated by Django 5.1.15 on 2026-05-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_demand_schedule_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='visibility_mode',
            field=models.CharField(choices=[('mode1', 'Mode 1 — Standard (information hidden)'), ('mode2', 'Mode 2 — Upstream sees downstream order')], default='mode1', max_length=10),
        ),
    ]
